### PR TITLE
Water filter support

### PR DESCRIPTION
**Pull request by bendavis**
Adds initial support for the [GE Whole Home Water filter](https://www.geapplianceparts.com/store/parts/spec/GXWH70M).

I outlined most of my initial investigation to #12. This work is sufficient to read the state of the water filter and statistics about use.

I also added a simple webclient call to get alert notifications at /v1/appliance/{mac}/message.

Still needed:
* A better understanding of how to change filter state between Filtered, Bypass and Off. I'm not sure of the relationship between erd values at 0x115f and 0x1160 for switching states.
* Write conversions (for example filter alert settings, filter state/valve state, manual/automatic mode)

### CODE REVIEW

**Comment by warrenrees** [comment]
Great job.  I can fill in some blanks based on the quick investigation I did into this:

0x115e
  public enum State {
        BYPASS(0),
        CLOSED(1),
        OPEN(2),
        MANUAL_OVERRIDE(3),
        DRIVING(4),
        FAULT(5),
        INVALID(6);

0x115f
  public enum WaterValveState {
        UNDEFINED(-1),
        BYPASS(0),
        CLOSED(1),
        FILTERED(2),
        TRANSITION(3);

0x1167
    public enum Position {
        BYPASS(0),
        OFF(1),
        FILTERED(2);

0x1168
  public enum ManualOverride {
        CLEAR(0),
        SET(1);

0x1169
    public enum ContinuousFlowAlert {
        CLEAR(0),
        LOW(1),
        MEDIUM(2),
        HIGH(4),
        RESERVED(8);

0x116e
    public enum LeakValidity {
        INACTIVE(0),
        INVALID(1),
        VALID(2);

My educated guess is that 0x1167 (WH_FILTER_POSITION) is used to control the device, so we'd need the erd_encode method on that.

This is what I had started:

wrees@eta:~/gehome-todo/gehomesdk/erd/values/waterfilter % more waterfilter_enums.py
import enum
from typing import NamedTuple, Optional

@enum.unique
class ErdWaterValveState(enum.Enum):
    UNDEFINED = -1
    BYPASS = 0
    CLOSED = 1
    FILTERED = 2
    TRANSITION = 3

@enum.unique
class ErdPosition(enum.Enum):
    BYPASS = 0
    OFF = 1
    FILTERED = 2

@enum.unique
class ErdContinuousFlowAlert(enum.Enum):
    CLEAR = 0
    LOW = 1
    MEDIUM = 2
    HIGH = 4
    RESERVED = 8

String conversions:

wrees@eta:~/gehome-todo/gehomesdk/erd/values/waterfilter % more water_valve_state.py
import enum

@enum.unique
class WaterValveState(enum.Enum):
    STATE_DASH = "---"
    STATE_BYPASS = "Bypass"
    STATE_CLOSED = "Water Flow Off"
    STATE_FILTERED = "Filtered"
    STATE_TRANSITION = "Transition"

    def stringify(self, **kwargs):
        return self.name.replace("STATE_","").replace("_"," ").title()

wrees@eta:~/gehome-todo/gehomesdk/erd/values/waterfilter % more water_valve_state_mapping.py
from .waterfilter_enums import ErdWaterValveState
from .water_valve_state import WaterValveState

WATER_VALVE_STATE_MAP = {
    ErdWaterValveState.UNDEFINED: WaterValveState.STATE_DASH,
    ErdWaterValveState.BYPASS: WaterValveState.STATE_BYPASS,
    ErdWaterValveState.CLOSED: WaterValveState.STATE_CLOSED,
    ErdWaterValveState.FILTERED: WaterValveState.STATE_FILTERED,
    ErdWaterValveState.TRANSITION: WaterValveState.STATE_TRANSITION
}

wrees@eta:~/gehome-todo/gehomesdk/erd/converters/waterfilter % more water_valve_state_converter.py
import logging

from gehomesdk.erd.converters.abstract import ErdReadOnlyConverter
from gehomesdk.erd.converters.primitives import *
from gehomesdk.erd.values.waterfilter import ErdWaterValueState, WaterValueState, WATER_VALVE_STATE_MAP

_LOGGER = logging.getLogger(__name__)

class WaterValveStateConverter(ErdReadOnlyConverter[WaterValveState]):
    def erd_decode(self, value: str) -> WaterValveState:
        try:
            om = ErdWaterValveState(erd_decode_int(value))
            return WATER_VALVE_STATE_MAP[om].value
        except (KeyError, ValueError):
            return ErdWaterValveState.UNDEFINED

**Comment by bendavis** [comment]
Thanks for filling in the missing holes - I think 0x1167 is still a bit odd because for me (my filter is set to filtered) I have these values:

{"erd":"0x115E","value":"02","time":"2021-06-27T10:38:20.322Z"},
{"erd":"0x115F","value":"02","time":"2021-06-27T10:38:20.322Z"},
{"erd":"0x1167","value":"03","time":"2021-06-27T10:38:20.322Z"}
{"erd":"0x1160","value":"0000","time":"2021-06-29T13:42:23.390Z"},
{"erd":"0x1163","value":"00","time":"2021-06-27T10:38:20.322Z"},{"erd":"0x1164","value":"000000310000322D0000002C","time":"2021-06-29T06:20:39.832Z"},{"erd":"0x1167","value":"03","time":"2021-06-27T10:38:20.322Z"}

So you can see that 0x115e and 0x115f are filtered but 0x1167 is 03. I've also observed that:

In a transition from bypass to filtered
0x1167 goes from 02->03

In a transition from filter to bypass
0x1167 goes from 03 -> 00 -> 03

Maybe 0x1167 at 03 means something like ready to post?

**Comment by warrenrees** [comment]
Hrm.. yeah that would make sense based on the behavior that you're seeing. 

The logic for setting it would be to check if it's set at 03, else wait because it's probably in the middle of a move operation.

**Comment by bendavis** [comment]
Okay I can confirm that the state changes when you write to 0x1167. I changed the corresponding ha_components branch to support the type as a 'select' type, and was able to change the filter mode by service. Neat.

**Pull request merged**
