### PR TITLE
- Update Remote Delay start to use timedelta via time span converter

### PR DESCRIPTION
**Pull request by warrenrees**

### CODE REVIEW

**Comment by simbaja** [comment]
crap, didn't see this and actually made similar updates.  I think I've made the configuration change which was the only piece needed.  during my commits, I actually changed the defaults as I noticed that the existing timespans were all 2 bytes.

I think we can abandon this PR, agree?

**Comment by warrenrees** [comment]
Yep, can you just update the erd_configurwtion file and point the delay control to the timespan converter?

**Comment by simbaja** [comment]
Yep, did that after I saw your PR :)

**Comment by warrenrees** [comment]
Have you push it up, it doesn't appear to be showing yet on my end.

**Comment by simbaja** [comment]
Ha, oops.

**Comment by warrenrees** [comment]
Ahh there it is. Thanks.

**Pull request closed without merging**
